### ISSUE TITLE
alter account migration removes votes column

### ISSUE THREAD

**Issue by flashadvocate** [Thibaud-DT/trinitycore-auth#6]
Just curious why this column (https://github.com/Thibaud-DT/trinitycore-auth/blob/master/database/migrations/2016_12_20_151524_alter_account_table.php#L35) is removed as part of the `down()` method when it isn't a part of the `up()` method.

Working on trying to get unit tests working with database migrations, but want to understand the reason for this

**Comment by Thibaud-DT** [comment]
If you using Passport Package, you need a password column hash with bcrypt instead of TrinityCore hash system.

So, in the up() method, I create the column "password" if the config('trinitycore-auth.passport') is true, and I drop it if the column password exist.

For the "remerber_token" column, it doesn't exist in TrinityCore Account table. So i create it if it doesn't exist (with it almost always true) https://github.com/Thibaud-DT/trinitycore-auth/blob/master/database/migrations/2016_12_20_151524_alter_account_table.php#L17 and I drop it in the down() method.

**Comment by flashadvocate** [comment]
Yeah, I realized later on that it was just a typo (it was dropping a votes column). The conditional didn't match the action :P
